version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/grepai
    binary: grepai
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Other Changes"
      order: 999

release:
  github:
    owner: yoanbernabeu
    name: grepai
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## grepai {{ .Version }}

    Semantic code search CLI tool.
  footer: |
    ---

    **Full Changelog**: https://github.com/yoanbernabeu/grepai/compare/{{ .PreviousTag }}...{{ .Tag }}

# Homebrew tap can be added later when homebrew-tap repo is created
# brews:
#   - repository:
#       owner: yoanbernabeu
#       name: homebrew-tap
#     directory: Formula
#     homepage: https://github.com/yoanbernabeu/grepai
#     description: "Privacy-first semantic code search CLI"
#     license: MIT
